version: '3.7'
services:
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment: 
      MYSQL_ROOT_PASSWORD: whatever
    volumes:
      - "dev-mysql-data:/var/lib/mysql"
    ports:
      - 3306:3306
  oracle:
    image: epiclabs/docker-oracle-xe-11g
    restart: always
    environment: 
      ORACLE_ALLOW_REMOTE: 'true'
      ORACLE_PASSWORD: otro
      RELAX_SECURITY: 1
    ports:
      - 1521:1521
    volumes:
      - "dev-oracle-data:/u01/app/oracle"

   


volumes:
  dev-mysql-data:
  dev-oracle-data:



